- name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.160.1'
          extended: true

      - name: Install Hugo Modules  # 新增：自动下载主题
        run: hugo mod get -u

      - name: Build
        run: hugo --minify